### ISSUE TITLE
Script error when MI cannot be found

### ISSUE THREAD

**Issue by extmaper** [JulianHayward/AzADServicePrincipalInsights#10]
Error according to screenshot running latest version.

![image](https://user-images.githubusercontent.com/56257151/196111713-21ae7d5a-0fe2-4cc4-8ff4-cbda9ea97f43.png)

**Comment by JulianHayward** [comment]
the MI resource still exists or has been deleted meanwhile?

**Comment by extmaper** [comment]
The MI doesn't exist. I have run the pipeline multiple times, but it fails on the same every time.

**Comment by JulianHayward** [comment]
interesting! the resource obviously has been returned from ARM as an existing resource (https://learn.microsoft.com/en-us/rest/api/resources/resources/list)

Can you ping me on LinkedIn?

**Comment by JulianHayward** [comment]
released v1_20221017_1; finding: non existent resource(s) only returned if connected as Service Principal

**Comment by extmaper** [comment]
Works fine after latest update. Thanks for quick response and action.
