### ISSUE TITLE
Access token has expired or is not yet valid

### ISSUE THREAD

**Issue by ezequielan** [JulianHayward/AzADServicePrincipalInsights#11]
Hi,
we are trying to run this solution against out Azure management group but we have so many data that the process takes more than 1hour but the token adquired only last 1h and it is not refreshed during the process, so it's faliling, what can we do in this case?, thanks.

![image](https://user-images.githubusercontent.com/79863609/197003796-50f9768a-0948-47af-966a-4a5f52a86cfe.png)

**Comment by JulianHayward** [comment]
@ezequielan are you sure that it is failing? is it in an endless loop 'requesting new bearerToken' or do you just see that for a certain period (it is running in parallel, so you will see the error multiple times, but it should actually get the new token after a short time period and continue)..

**Comment by ezequielan** [comment]
@JulianHayward i'll try tomorrow to let the process run more time but since the error i've let the process run like 30 minutes and was stucked in that loop.

**Comment by ezequielan** [comment]
Hello @JulianHayward,
the process is still running after almost 4 hours, i only see this "progress" after the bearer token errors started to appear:
![image](https://user-images.githubusercontent.com/79863609/197203747-0bf0ef1e-aa21-4b4f-802f-73d84c494620.png)

Thanks

**Comment by JulianHayward** [comment]
@ezequielan can you contact me on LinkedIn?

**Comment by JulianHayward** [comment]
works as designed, self hosted worker connectivity in doubt :)
