### ISSUE TITLE
Add parameters overview in README.md

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/AzADServicePrincipalInsights#12]
Hi,

is it possible to update the README with an overview of the parameters possible?

Thanks in advance

**Comment by JulianHayward** [comment]
hi @MarcelHeek please feel free to PR a first draft, I can complete those that you are unclear on.

**Comment by MarcelHeek** [comment]
I knew my request would backfire 😜
Will try to find the time to do so 👍

**Comment by JulianHayward** [comment]
thanks - merged
