### ISSUE TITLE
get AAD RoleDefinitions --> Authorization_RequestDenied

### ISSUE THREAD

**Issue by MarcelHeek** [JulianHayward/AzADServicePrincipalInsights#14]
Hi,

I am building a Github workflow to run the datacollection on a self-hosted GitHub runner. This runner  has a (user assigned) Managed Identity that has the following API permissions.
![image](https://user-images.githubusercontent.com/84451910/210558011-a842d8dd-5bdf-452c-a9db-15077313ecd3.png)
Additionally the MI has the Reader role assignment assigned at the Tenant Root Group
![image](https://user-images.githubusercontent.com/84451910/210558413-01d41e7f-c6aa-48ef-9706-5b1bf245ac57.png)

According to the documentation that should be the assigned permissions (I use the same MI for AzGovRep data collection), however the script fails with the following dump:

  ```
Getting 430 Service Principals duration: 0.0379013133333333 minutes (2.2740788 seconds)
  Creating mapping AppRoles & PublishedPermissionScopes
  Getting all AAD Role definitions
  - - - - - - - - - - - - - - - - - - - - 
  !Please report at aka.ms/AzADServicePrincipalInsights and provide the following dump
  get AAD RoleDefinitions - try #1; returned: (StatusCode: '403' (Forbidden)) <.code: ''> <.error.code: 'Authorization_RequestDenied'> | <.message: ''> <.error.message: 'Insufficient privileges to complete the operation.'> - (plain : @{error=}) - EXIT
  Parameters:
  accountType:ManagedService
  azAccountsVersion:2.10.4
  azAPICallModuleVersion:1.1.40
  codeRunPlatform:GitHubActions
  debugAzAPICall:False
  debugWriteMethod:Host
  gitHubRepository:aka.ms/AzADServicePrincipalInsights
  NoAzureResourceSideRelations:False
  NoJsonExport:False
  onAzureDevOps:False
  onAzureDevOpsOrGitHubActions:True
  onGitHubActions:True
  OnlyProcessSPsThatHaveARoleAssignmentInTheRelevantMGScopes:False
  ProductVersion:v1_20221017_1
  psVersion:7.3.1
  subscriptionQuotaId:MSDNDevTest_2014-09-01
  userType:n/a
  writeMethod:Host
  Exception: 
  Line |
   541 |              Throw 'Error - check the last console output for details'
       |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       | Error - check the last console output for details
  Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

I am converting the workflow from the use of Service Principal to Managed Identity. Using a Service Principal works without errors. 

Please advice.

**Comment by JulianHayward** [comment]
I agree, the permissions are looking good [docs](https://learn.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions).  
<img width="593" alt="image" src="https://user-images.githubusercontent.com/45695032/210569260-60b32a18-485b-413b-b286-04e98375054d.png">

Did you grant permissions only recently?

**Comment by MarcelHeek** [comment]
Yes, 13:31 CET, so quite recently. Just gave it another try and still failing with same privilege error

**Comment by JulianHayward** [comment]
hmm, let´s give it another 30 mins, then use the next available permission (dir.read.all)?

**Comment by MarcelHeek** [comment]
First attempt after granting "Directory.Read.All" still results in failure. Will try again in a couple of hours.
