### ISSUE TITLE
CsvDelimiter parameter only works for 2 CSV files

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#15]
After adding the -CsvDelimiter "," parameter when running the script, only 2 CSVs switched to using the proper delimiter:

- perf.csv
- ManagedIdentityUserAssignedAssociatedAzureResources.csv

All the other CSV files are still using the ";" delimiter.

**Comment by JulianHayward** [comment]
@cjtous1 thanks for reporting. Do you want to file a PR (search export-csv)?
