### ISSUE TITLE
Improvement - Add SPTags to Service Principals HTML/CSV?

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#17]
Hello,
I can see in the raw JSON data that the Service principal tags are available (SPTags).
Would it be possible to add a column for Service Principal tags?
I looked at the script but I am not exactly sure where I could add this in the script.
If you can give me a bit of guidance, I could try to do the modification myself and submit a pull request.
Thank you.

**Comment by JulianHayward** [comment]
hi @cjtous1 

for the html 
<img width="99" alt="image" src="https://github.com/JulianHayward/AzADServicePrincipalInsights/assets/45695032/ce243eec-02ab-49e7-b7d0-22496c813673">:

Will you consider SPTags as well as APPTags?  
start from here:  
https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/2971d108a344f4eccb5e5557fee000e5bb6c2734/pwsh/AzADServicePrincipalInsights.ps1#L1352

Iterate the tags arrays and join by `$CsvDelimiterOpposite`

I note that for this we do not have a automatically generated csv for the html section 'service principals' but exportable csv from the html file..

looking forward to your PR

**Comment by JulianHayward** [comment]
@cjtous1 sure thing!
I have seen scenarios where e.g. AppTags are filled with an escaped JSON format. Can you please try to consider that / check if that causes any issues?

Example:
```JSON
{
  "APPTags": [
    "{\"responsibility\":{\"NotificationEmailAddress\":[\"name0.surname@contoso.com\",\"name1.surname2@contoso.com\"],\"responsiblePerson\":\"name2.surname@contoso.com\",\"responsibleTeam\":\"Awesome Team\"}}"
  ]
}
```
