### ISSUE TITLE
Fix/Improvements to CSV and JSON exports

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#19]
It looks like NoJsonExport and NoCsvExport are not being used in the script to prevent CSV and JSON files from being generated by the script.
I would like to work on adding a couple of if statements to prevent CSV & JSON files from being generated if the those parameters are set to true.

Also, I would also like to add missing CSV files for some of the tables present in the HTML page. Are there any gotchas that I should be aware of before attempting to do that?
Thanks.

**Comment by JulianHayward** [comment]
sounds good!

One thing to consider for JSON export: if the script is executed in a pipeline (AzDO or GH) and noJSONExport is true then we loose the detailed history tracking via git (intentionally or not..). So I´d say let´s only support the noJSONExport outside of pipeline execution OR introduce a new explicit parameter e.g. `-NoJsonExportWhenOnAzureDevOpsOrGitHubActions`?

Ref: AzAPICall checks the [codeRunPlatform](https://github.com/JulianHayward/AzAPICall/blob/407abbb46ebf6381294ccf42f87cc2251d3048b5/pwsh/module/dev/AzAPICall/functions/setHtParameters.ps1#L31)
```powershell
#[bool]
$azAPICallConf['htParameters'].onAzureDevOpsOrGitHubActions
```

**Comment by JulianHayward** [comment]
hi, thing is that in most scenarios you test locally/console, here the JSON export may be experienced as noise and the history tracking scenario in git may not be considered - therefore the concern. I think I prefer the variant of introducing a new explicit parameter e.g. -NoJsonExportWhenOnAzureDevOpsOrGitHubActions. Anyways you don´t need to bother with that, it can be adjusted afterwards..

Please keep working against the open PR.

thanks.

**Comment by JulianHayward** [comment]
hey @cjtous1 great job! 
two things
* please keep the extra '_' at the end of the csv files - why? consider all the existing deployments out there in the wild / those would get new files and therefore loose history..
* when exporting please stick to conditional file naming (local: we **don´t** want to overwrite files; onAzureDevOpsOrGitHubActions we **do** want to overwrite files
e.g.
```powershell
        if ($azAPICallConf['htParameters'].onAzureDevOpsOrGitHubActions -eq $true) {
            $fileName = "$($Product)_$($fileNameMGRef)_HiPoUsers_"
        }
        else {
            $fileName = "$($Product)_$($ProductVersion)_$($fileTimestamp)_$($fileNameMGRef)_HiPoUsers_"
        }
        $arrayHiposSorted | Select-Object -ExcludeProperty permission4HTML | Export-Csv -Path "$($outputPath)$($DirectorySeparatorChar)$($fileName).csv" -Delimiter "$csvDelimiter" -Encoding utf8 -NoTypeInformation -UseQuotes AsNeeded
```

**Comment by JulianHayward** [comment]
hi @cjtous1,oha - yes please go ahead
