### ISSUE TITLE
Dumb "StatusCode: '404' (NotFound)" when checking permissions on Management Group

### ISSUE THREAD

**Issue by KaveSys** [JulianHayward/AzADServicePrincipalInsights#22]
Hello,
I want to use this tool via Powershell, but when I try to run the command:

.\AzADServicePrincipalInsights.ps1

I receveive on this step an error (removed company ID information):

Start AzADServicePrincipalInsights 30-Nov-2023 10:17:23 (#v1_20231121_1)
 Checking PowerShell edition and version
  PS check passed : (Major[7]; Minor[4] gt 0); (minimum supported version '7.0.3')
  PS Edition: Core; PS Version: 7.4.0
  PS Version check succeeded
Output/Files will be created in path 'C:\Users\lcavagna\Downloads\AzADServicePrincipalInsights-main\AzADServicePrincipalInsights-main\pwsh\.'
 Verify 'AzAPICall' (1.1.84)
Initialize 'AzAPICall'
 AzAPICall 1.1.84
 Check required Az modules cmdlets
  Az PS module supporting cmdlet 'Get-AzContext' installed
  Az Module Az.Accounts Version: could not be assessed
  Required Az modules cmdlets check succeeded
 Create htParameters
  codeRunPlatform: Console
  AzAPICall debug disabled
 AzAPICall htParameters:

Name                                Value
----                                -----
debugAzAPICall                      False
onAzureDevOpsOrGitHubActions        False
gitHubRepository                    aka.ms/AzADServicePrincipalInsights
psVersion                           7.4.0
codeRunPlatform                     Console
subscriptionId4AzContext
onAzureDevOps                       False
onGitHubActions                     False
debugWriteMethod                    Host
skipAzContextSubscriptionValidation True
azAccountsVersion                   n/a
tenantId4AzContext                  <deleted for information>
writeMethod                         Host
azAPICallModuleVersion              1.1.84

  Create htParameters succeeded
 Get Az context
  Azure cloud environment: AzureCloud
  Get Az context succeeded
 Set environment endPoint url mapping
  Check endpoint: 'ARM'; endpoint url: 'https://management.azure.com/'
  Check endpoint: 'KeyVault'; endpoint url: 'https://vault.azure.net'
  Check endpoint: 'LogAnalytics'; endpoint url: 'https://api.loganalytics.io'
  Check endpoint: 'MicrosoftGraph'; endpoint url: 'https://graph.microsoft.com'
  Check endpoint: 'Login'; endpoint url: 'https://login.microsoftonline.com'
  Check endpoint: 'Storage'; endpoint url: 'core.windows.net'
  Add to endpoint: 'Storage'; endpoint url: 'storage.azure.net'
  Set endpoint: 'Kusto'; endpoint url: 'kusto.windows.net'
  Set environment endPoint url mapping succeeded
 Check Az context
  Az context AccountId: 'lcavagna@evocagroup.com'
  Az context AccountType: 'User'
  Az context related parameters: -SubscriptionId4AzContext==''; -TenantId4AzContext=='<deleted for information>'; -SkipAzContextSubscriptionValidation=='True'
  Az context is already set to TenantId: '<deleted for information>'
  Stay with current Az context: Tenant:'<deleted for information>' Subscription:' ()'
   Az context Tenant: '<deleted for information>'
   Az context Subscription check skipped ($SkipAzContextSubscriptionValidation==True) - no Subscription in context
  Az context check succeeded
 Check AAD UserType
 +Processing new bearer token request 'MicrosoftGraph' "https://graph.microsoft.com"
 +Bearer token 'MicrosoftGraph': [tokenRequestProcessed: '11/30/2023 10:17:23']; [expiryDateTime: '12/01/2023 10:15:30']; [timeUntilExpiry: '23:58:06.3131970']
  AAD UserType: Member; AAD identityId: <deleted for information>
  AAD UserType check succeeded
  Get ARM locations
   Get ARM locations not possible (no subscription in current context). Either use parameter -SubscriptionId4AzContext (initAzAPICall -SubscriptionId4AzContext <subscriptionId>) or if you do not have any subscriptions then you won´t be able to address regional endpoints e.g. 'https://westeurope.management.azure.com/' (info: parameter $SkipAzContextSubscriptionValidation = True)
 Initialize 'AzAPICall' succeeded
Executing against Tenant Root Group: True
Executing against 1 ManagementGroup(s): <deleted for information>
Add AzADServiceprincipalInsights htParameters
htParameters:

Name                                                       Value
----                                                       -----
NoAzureResourceSideRelations                               False
azureCloudEnvironment                                      AzureCloud
ARMLocations                                               {}
onGitHubActions                                            False
userType                                                   Member
debugAzAPICall                                             False
OnlyProcessSPsThatHaveARoleAssignmentInTheRelevantMGScopes False
onAzureDevOpsOrGitHubActions                               False
gitHubRepository                                           aka.ms/AzADServicePrincipalInsights
ProductVersion                                             v1_20231121_1
psVersion                                                  7.4.0
codeRunPlatform                                            Console
subscriptionId4AzContext
onAzureDevOps                                              False
accountType                                                User
NoJsonExport                                               False
debugWriteMethod                                           Host
skipAzContextSubscriptionValidation                        True
azAccountsVersion                                          n/a
tenantId4AzContext                                         <deleted for information>
writeMethod                                                Host
userObjectId                                               <deleted for information>
azAPICallModuleVersion                                     1.1.84

Add AzADServiceprincipalInsights htParameters succeeded
Verify Classifications (permissionClassification.json)
 Verify Classifications (permissionClassification.json) succeeded
Running AzADServicePrincipalInsights for ManagementGroupId: '<deleted for information>'
Checking permissions for ManagementGroup '<deleted for information>'
 +Processing new bearer token request 'ARM' "https://management.azure.com"
 +Bearer token 'ARM': [tokenRequestProcessed: '11/30/2023 10:17:24']; [expiryDateTime: '11/30/2023 11:21:59']; [timeUntilExpiry: '01:04:34.5079807']
- - - - - - - - - - - - - - - - - - - -
**!f97434b8 Please report at aka.ms/AzADServicePrincipalInsights and provide the following dump
[AzAPICallErrorHandler 1.1.84] Checking permissions for ManagementGroup '<deleted for information>' try #1; uri:"https://management.azure.com/providers/Microsoft.Management/managementGroups/<deleted for information>?api-version=2020-05-01"; return: (StatusCode: '404' (NotFound)) <.code: ''> <.error.code: 'NotFound'> | <.message: ''> <.error.message: ''/providers/Microsoft.Management/managementGroups/<deleted for information>' not found'> - (plain : @{error=}) - AzAPICall: Stop**
Parameters:
accountType:User
ARMLocations:
azAccountsVersion:n/a
azAPICallModuleVersion:1.1.84
azureCloudEnvironment:AzureCloud
codeRunPlatform:Console
debugAzAPICall:False
debugWriteMethod:Host
gitHubRepository:aka.ms/AzADServicePrincipalInsights
NoAzureResourceSideRelations:False
NoJsonExport:False
onAzureDevOps:False
onAzureDevOpsOrGitHubActions:False
onGitHubActions:False
OnlyProcessSPsThatHaveARoleAssignmentInTheRelevantMGScopes:False
ProductVersion:v1_20231121_1
psVersion:7.4.0
skipAzContextSubscriptionValidation:True
subscriptionId4AzContext:
tenantId4AzContext:<deleted for information>
userObjectId:<deleted for information>
userType:Member
writeMethod:Host
[AzAPICallErrorHandler 1.1.84] Checking permissions for ManagementGroup '<deleted for information>' try #1; uri:"https://management.azure.com/providers/Microsoft.Management/managementGroups/<deleted for information>?api-version=2020-05-01"; return: (StatusCode: '404' (NotFound)) <.code: ''> <.error.code: 'NotFound'> | <.message: ''> <.error.message: ''/providers/Microsoft.Management/managementGroups/<deleted for information>' not found'>  - unhandledErrorAction: Stop
Exception:
Line |
 832 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details
PS C:\Users\lcavagna\Downloads\AzADServicePrincipalInsights-main\AzADServicePrincipalInsights-main\pwsh>

**Comment by JulianHayward** [comment]
@KaveSys do you actually have management groups and did you apply all required permissions as per https://github.com/JulianHayward/AzADServicePrincipalInsights#permissions

**Comment by JulianHayward** [comment]
super :) -closing
