### ISSUE TITLE
Feature request: Include publish to web app in pipelines

### ISSUE THREAD

**Issue by RS-MPersson** [JulianHayward/AzADServicePrincipalInsights#23]
Feature request to add option in pipelines to publish result to web app in the same way as with AzGovViz.

**Comment by JulianHayward** [comment]
@RS-MPersson yes - good one - expecting your PR :) let me know if support needed

**Comment by RS-MPersson** [comment]
https://github.com/JulianHayward/AzADServicePrincipalInsights/pull/24

**Comment by JulianHayward** [comment]
merged
