### ISSUE TITLE
Log Ingestion - Schema for Table/DCR?

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#29]
Looking at the new script to perform log ingestion, it seems like the function to generate sample data is gone from the script.
Would it be possible to provide the schema that we should use for the custom table/DCR?

Since there are many different properties that SPs can contain, I want to make sure my schema definition is valid for all the different types captured by this solution.

**Comment by JulianHayward** [comment]
likely to provide a dummy file in the repo. thanks.
