### ISSUE TITLE
Log Ingestion - ContentLengthLimitExceeded

### ISSUE THREAD

**Issue by cjtous1** [JulianHayward/AzADServicePrincipalInsights#30]
I started testing log ingestion in my test tenant and I am getting the following error:

`[AzAPICallErrorHandler 1.2.0] Batch#0; Process file 158/1268; Ingesting data for ObjectType=SP APP EXT, SPDisplayName=Microsoft Graph, SPObjectId=<OBJECTID>, SPAppId=00000003-0000-0000-c000-000000000000 try #1; uri:"https://<DCE>.ingest.monitor.azure.com/dataCollectionRules/<DCR>/streams/Custom-AzADServicePrincipalInsights_CL?api-version=2023-01-01"; return: (StatusCode: '413' (RequestEntityTooLarge)) <.code: ''> <.error.code: 'ContentLengthLimitExceeded'> | <.message: ''> <.error.message: 'Maximum allowed content length: 1048576 bytes (1 MB). Provided content length: 1068792 bytes.'> - (plain : @{error=}) - AzAPICall: Stop`

I tried lowering the throttle down to 1 and it still fails. It seems like the service principal for Microsoft Graph is too large.
Is this something you encountered in your testing?
Is there something I can modify to allow larger content?

**Comment by JulianHayward** [comment]
@Cloud-Architekt Thomas any ideas?

**Comment by Cloud-Architekt** [comment]
Yes, otherwise we can also consider to exclude app roles for first party apps (such as Microsoft Graph API) to reduce unnecessary data. @cjtous1: Do you see any scenarios where this details would be helpful?

**Comment by JulianHayward** [comment]
thanks @cjtous1 need to look into this, too. So actually **NO** entry shows up in LA table?

**Comment by JulianHayward** [comment]
@cjtous1 I intentionally did not, but yes - if you think it will help please feel free to pr. Thanks
