### ISSUE TITLE
Use case: AzADServicePrincipalInsights for Entra ID tenant only 

### ISSUE THREAD

**Issue by horgasz2023** [JulianHayward/AzADServicePrincipalInsights#34]
Hello,

we are trying to run your solution against a test Entra ID tenant but the script keeps failing on the Management group check. As we do not have any Azure subscription associated to our Test tenant we cannot move on. Is there any way to limit the scope to an Entra ID tenant?later we might test it with an Azure subscription too but now we need the Entra ID tenant only.

We have currently the following error:

Add AzADServiceprincipalInsights htParameters succeeded
Verify Classifications (permissionClassification.json)
Verify Classifications (permissionClassification.json) succeeded
Checking ServicePrincipal permissions
+Processing new bearer token request 'MicrosoftGraph' "
https://graph.microsoft.com"
+Bearer token 'MicrosoftGraph': [tokenRequestProcessed: '05.16.2024 12:29:55']; [expiryDateTime: '05/17/2024 12:29:56']; [timeUntilExpiry: '1.00:00:00.9529389']
Running AzADServicePrincipalInsights for ManagementGroupId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
Checking permissions for ManagementGroup 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
+Processing new bearer token request 'ARM' "
https://management.azure.com"
+Bearer token 'ARM': [tokenRequestProcessed: '05.16.2024 12:29:56']; [expiryDateTime: '05/16/2024 13:29:58']; [timeUntilExpiry: '01:00:01.2617496']
[AzAPICallErrorHandler 1.2.0] Checking permissions for ManagementGroup 'xxxxxxxxxxxxxxxxxxxxxxxxx' try #1; uri:"
[https://management.azure.com/providers/Microsoft.Management/managementGroups/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx?api-version=2020-05-01";](https://management.azure.com/providers/Microsoft.Management/managementGroups/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?api-version=2020-05-01%22;)
return: (StatusCode: '403' (Forbidden)) <.code: ''> <.error.code: 'AuthorizationFailed'> | <.message: ''> <.error.message: 'The client 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' with object id 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Management/managementGroups/read' over scope '/providers/Microsoft.Management/managementGroups/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials.'> - AzAPICall: return 'failed'
Permission check results
AAD Users Read permission check PASSED
AAD Groups Read permission check PASSED
AAD ServicePrincipals Read permission check PASSED
AAD RoleManagement Read permission check PASSED
MG 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' Reader permission check FAILED
Please consult the documentation:
https://aka.ms/AzAPICall#required-permissions-in-azure
Exception: C:\Test\ServicePrincipalsReporting\AzADServicePrincipalInsights.ps1:5041
Line |
5041 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
hi @horgasz2023 
hmm, the errors and the information you provided do not really match.
1. The AzAPICall should have thrown if there was no subscription in the azContext
2. Do you have Management Group setup in that tenant? If yes, then make sure that RBAC Reader role is assigned to the executing principal. If not, then please try creating one.

**Comment by horgasz2023** [comment]
so we ve created a MG under the root management group and added the SP with RBAC Read but the script keeps failing for the Root Management Group Read permissions that is grayed out and we cannot add there the Read RBAC.

Permission check results
AAD Users Read permission check PASSED
AAD Groups Read permission check PASSED
AAD ServicePrincipals Read permission check PASSED
AAD RoleManagement Read permission check PASSED
  MG 'ROOT MANAGEMENT GROUP' Reader permission check FAILED
Please consult the documentation:
https://aka.ms/AzAPICall#required-permissions-in-azure
Exception: C:\Test\ServicePrincipalsReporting\AzADServicePrincipalInsights.ps1:5041
Line |
5041 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details 

Why we cannot edit the permissions of the Root Management Group?can we add there the SP?any hint what we can do about it?

**Comment by horgasz2023** [comment]
meanwhile found that User Access Administrator is needed to add RBAC Read for the Root MG.

**Comment by horgasz2023** [comment]
new error:

MG 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx' Reader permission check PASSED
Getting Entities
Getting Entities duration: 0.3613898 seconds
Getting all Subscriptions
Getting all Subscriptions duration: 0.2803042 seconds
-Getting child Subscriptions for ManagementGroup scope xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Caching built-in Role definitions
- - - - - - - - - - - - - - - - - - - -
!f97434b8 Please report at aka.ms/AzAPICall and provide the following dump
[AzAPICallErrorHandler 1.2.0] Caching built-in Role definitions try #1; uri:"
https://management.azure.com/subscriptions//providers/Microsoft.Authorization/roleDefinitions?api-version=2018-07-01&$filter=type
eq 'BuiltInRole'"; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidSubscriptionId'> | <.message: ''> <.error.message: 'The provided subscription identifier 'providers' is malformed or invalid.'> - (plain : @{error=}) - AzAPICall: Stop
Parameters:
accountType:ServicePrincipal
ARMLocations:
azAccountsVersion:n/a
azAPICallModuleVersion:1.2.0
azureCloudEnvironment:AzureCloud
codeRunPlatform:Console
debugAzAPICall:False
debugWriteMethod:Host
gitHubRepository:aka.ms/AzAPICall
NoAzureResourceSideRelations:False
NoJsonExport:False
onAzureDevOps:False
onAzureDevOpsOrGitHubActions:False
onGitHubActions:False
OnlyProcessSPsThatHaveARoleAssignmentInTheRelevantMGScopes:False
ProductVersion:v1_20240419_1
psVersion:7.4.2
skipAzContextSubscriptionValidation:True
subscriptionId4AzContext:
tenantId4AzContext:
userType:n/a
writeMethod:Host
[AzAPICallErrorHandler 1.2.0] Caching built-in Role definitions try #1; uri:"
https://management.azure.com/subscriptions//providers/Microsoft.Authorization/roleDefinitions?api-version=2018-07-01&$filter=type
eq 'BuiltInRole'"; return: (StatusCode: '400' (BadRequest)) <.code: ''> <.error.code: 'InvalidSubscriptionId'> | <.message: ''> <.error.message: 'The provided subscription identifier 'providers' is malformed or invalid.'>  - unhandledErrorAction: Stop
Exception:
Line |
841 |              Throw 'Error - check the last console output for details'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
hmm, k .. try using the parameter `-NoAzureResourceSideRelations` [ref](https://github.com/JulianHayward/AzADServicePrincipalInsights?tab=readme-ov-file#parameters)

**Comment by horgasz2023** [comment]
thanks for that ...this is a parameter for the script itself ...we figured out. It is working now. Issue can be closed.

**Comment by JulianHayward** [comment]
@horgasz2023 great! outputs helpful?

**Comment by horgasz2023** [comment]
yes. however we did not know that it will export also config of the apps in json format. also it is a question for us what kind of export is this? We are using M365DSC and we tried Entra Exporter too. So what is the purpose of the folder with the json files?

**Comment by JulianHayward** [comment]
@horgasz2023 the json files hold the enriched information which can also be viewed in the html. Ideally you run in ado/gh then you can use those files as change tracking or see another use case here: https://www.cloud-architekt.net/entra-workload-id-advanced-detection-enrichment/
