### ISSUE TITLE
Pipeline runs failing on "$splitPermissionGrant = ($permissionGrant.scope).split()"

### ISSUE THREAD

**Issue by kaiaschulz** [JulianHayward/AzADServicePrincipalInsights#35]
Hey @JulianHayward ,
we are getting with the old (_v1_20240212_1_) and the new version (_v1_20240419_1_) an error:
```POWERSHELL
InvalidOperation: 
Line |
 336 |  …             $splitPermissionGrant = ($permissionGrant.scope).split('  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
##[error]PowerShell exited with code '1'.
```
With this error, the pipeline in one of of our tenant isn't running since several weeks.

**Comment by JulianHayward** [comment]
hey @kaiaschulz 
so this seems to happen here: https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/dcb3fd54a64c970cfa73b21fd8fbd1e203f7f7c9/pwsh/AzADServicePrincipalInsights.ps1#L5835
I cannot repro the issue - could you relax the throttlelimit and dump the currenttask? Then off the pipeline check the why/what?
thanks!

**Comment by kaiaschulz** [comment]
Hey @JulianHayward ,
I set the `ThrottleLimitARM` and `ThrottleLimitGraph` to `1`.
With that, it was easy to reproduce the failure and get the details of the call.
Afterwards, I repeated the call locally:
![image](https://github.com/JulianHayward/AzADServicePrincipalInsights/assets/58422100/640c9d1d-e8bc-4694-9607-ce69368b8f43)
As you can see, the REST API call response has a `scope` which is empty.
This should cause failing the pipeline.

**Comment by kaiaschulz** [comment]
It seems that the problem exists as well in https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/dcb3fd54a64c970cfa73b21fd8fbd1e203f7f7c9/pwsh/AzADServicePrincipalInsights.ps1#L6984

Already prepared a fork and a PullRequest will follow after a successful test.
