### ISSUE TITLE
error when i run the program

### ISSUE THREAD

**Issue by perrym** [JulianHayward/AzADServicePrincipalInsights#39]
when i run teh script these error
 
[AzAPICall 1.2.0] Forced DEBUG: getSP appRoleAssignedTo 3x5x47-7b4e-4xx-xxd-a99xxxxx7d63-> unexpectedError: true
[AzAPICall 1.2.0] getSP appRoleAssignedTo 3x5x47-7b4e-4xx-xxd-a99xxxxx7d633 try #7 'unexpectedError' occurred (tried 6 times) - unhandledErrorAction: Stop
Exception: C:\apps\azm\AzADServicePrincipalInsights-main\pwsh\AzADServicePrincipalInsights.ps1:5509
Line |
5509 |      $SPsAndAppsWithoutSPBatch | ForEach-Object -Parallel {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error - check the last console output for details

**Comment by JulianHayward** [comment]
@perrym can you try to debug this a bit. Lower the throttlelimit to 1, find the section in the script and dump related data. thanks.

**Comment by JulianHayward** [comment]
strike

**Comment by perrym** [comment]
Seen that troteling was the problem, thx
