### ISSUE TITLE
Feature request - Reporting on App Registration secrets with no expiry

### ISSUE THREAD

**Issue by bubbletroubles** [JulianHayward/AzADServicePrincipalInsights#5]
Is it possible to also report on app secrets which have no expiry?

**Comment by JulianHayward** [comment]
hmm, currently it reports all secrets.

noteworthy: 
* expired
* expires soon (14d)
* expires in more than 730 days

when you say no expiry there is no endDate set on that app? Please share an example from the json output file for one 'no expiry' app secret. -thanks

**Comment by JulianHayward** [comment]
closed / inactive
