### ISSUE TITLE
managementGroupIds parameter in DevOps pipelines

### ISSUE THREAD

**Issue by bubbletroubles** [JulianHayward/AzADServicePrincipalInsights#7]
The new parameter in DevOps pipelines (managementGroupIds) doesn't seem to work. When I run the pipeline but have the management group IDs blank, I get the error

`MG (mgId0) Reader permission check FAILED`

Reference to new code that was added.
https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/a095b45484fa6cd80da5bfc5c01909cc9daaf878/.azuredevops/pipelines/AzADServicePrincipalInsights.yml#L10-L14

How to use the pipeline to query on the root management group since the last release?

**Comment by JulianHayward** [comment]
updated the comments in the YAML file, does this help?

**Comment by bubbletroubles** [comment]
Yes that definately helps :)
