### ISSUE TITLE
Error during Enrichment - '$using:htCacheAssignmentsPolicy'

### ISSUE THREAD

**Issue by gettek** [JulianHayward/AzADServicePrincipalInsights#9]
Hi, I keep receiving the below error when running via AzDO, any help would be much appreciated!
```powershell
Enrichment starting prep
Enrichment completed prep
Enrichment starting
ForEach-Object: /azp/agent/_work/7/s/pwsh/AzADServicePrincipalInsights.ps1:6074
Line |
6074 | … s).where( { -not $_.MeanWhileDeleted } ) | ForEach-Object -Parallel {
| ~~~~~~~~~~~~~~~~~~~~~~~~~~
| The value of the using variable
| '$using:htCacheAssignmentsPolicy' cannot be retrieved because
| it has not been set in the local session.
##[error]PowerShell exited with code '1'.
```

I have a feeling the same may trigger for the [variables below](https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/main/pwsh/AzADServicePrincipalInsights.ps1#L6099-#L6116) also

**Comment by JulianHayward** [comment]
hmm, have you modified anything? Are you using any parameters?
Could you try to launch the script from any local console [hlp_ConnectAsSP.ps1](https://github.com/JulianHayward/AzADServicePrincipalInsights/blob/main/pwsh/hlp_ConnectAsSP.ps1)?

**Comment by gettek** [comment]
I'm using a wrapper file to execute could this be the cause? Nothing has changed in the actual script

**Comment by JulianHayward** [comment]
then I must ask: does it work without the wrapper?

**Comment by gettek** [comment]
It does indeed, I'll keep testing but guessing its to do with how the session is invoked from the wrapper. I'd rather not use a wrapper at all but unfortunately needed in my use case :( thanks, will keep you posted

**Comment by gettek** [comment]
Dot-sourcing seems to do the trick!

```powershell
$parameters = @{
    ScriptPath = "AzAdInsights"
    azAPICallVersion = '1.1.23'
    OutputPath = "$workspace/output/$tenant"
    FileTimeStampFormat = "dd_MM_yyy_HHmmss"
    ApplicationSecretExpiryWarning = 14
    ApplicationSecretExpiryMax = 90
    ApplicationCertificateExpiryWarning = 14
    ApplicationCertificateExpiryMax = 90
}
try {
    . "$workspace/AzADServicePrincipalInsights.ps1" @parameters -NoJsonExport
}
catch {
    Write-Output "Could not complete Insights Collection: $_"
    Break
}
```
The below do not work:
```powershell
# 1
Invoke-Expression "$workspace/AzADServicePrincipalInsights.ps1" @parameters -NoJsonExport
#2
& "$workspace/AzADServicePrincipalInsights.ps1" @parameters -NoJsonExport
# 3
"$workspace/AzADServicePrincipalInsights.ps1" @parameters -NoJsonExport
```
